config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian" ]
  validates :name, :address, :category, :telephone, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, :content, presence: true
  validates :rating, inclusion: { in: (0..5) }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(params_restaurant)
    redirect_to restaurant_path(@restaurant.id)
  end

  private

  def params_restaurant()
    params.require(:restaurant).permit(:name, :address, :telephone, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # def new
  #   @review = Review.new
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  # end

  def create
    @review = Review.new(params_review)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end

  end

  private

  def params_review
    params.require(:review).permit(:rating, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpMvpRevision</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_banner.html.erb
<div class="banner">
  <%= image_tag "styles-dessin-main-pour-articles-restaurant-restaurant-doodle_137262-191.avif" %>
  <div class="container">
    <h1>Welcome to Yelp!</h1>
    <p>See all restaurants above</p>
  </div>
</div>

app/views/restaurants/_formresto.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class= "col-xs-12 col-sm-4 col-sm-offset-4">
      <%= simple_form_for [@restaurant] do |f| %>
        <%= f.input :name%>
        <%= f.input :address%>
        <%= f.input :telephone%>
        <%= f.input :category, collection: Restaurant::CATEGORIES  %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/_navbar.html.erb
    <div class="navbar navbar-expand-lg navbar-light bg-dark navbar-dark border-bottom">
      <div class="container">
        <div style="color: #FFFFFF">Edit</div>
        <div style="color: #FFFFFF">Add</div>
        <!-- turn this link into a button -->
        <div><%= link_to 'Add restaurant', new_restaurant_path(), class: 'btn btn-primary' %></div>
        <%# <a href="#" class="btn btn-primary"></a> %>
      </div>
    </div>

app/views/restaurants/index.html.erb
<%= render 'navbar' %>
<%= render 'banner' %>

<h1>All restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <p><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
<% end  %>

<%= link_to 'Add restaurant', new_restaurant_path() %>

app/views/restaurants/new.html.erb
<h2>Add a new restaurant</h2>


<%= render "formresto" %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

<p>Address :<%= @restaurant.address %> </p>
<p>Telephone : <%= @restaurant.telephone %> </p>
<p>Category: <%= @restaurant.category %> </p>
<p>Reviews:</p>
<% @restaurant.reviews.each do |r|%>
 <p> rating: <%= r.rating %> <br> content : <%= r.content %>
</p>
<% end %>


<%# <%= link_to 'Add a review', new_restaurant_review_path(@restaurant.id) %>
<div class="container">
  <div class="row justify-content-center">
    <div class= "col-xs-12 col-sm-4 col-sm-offset-4">
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :rating, collection: 0..5%>
        <%= f.input :content%>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>